serviceName: "frontend"
namespace: "cloudmart-prod"
replicaCount: 1

image:
  repository: "787308166325.dkr.ecr.ap-south-1.amazonaws.com/cloudmart/frontend"
  tag: "52c23152675445d76ab26405adf6332ca9c1a257"

service:
  type: "ClusterIP"
  port: 80
  targetPort: 80

probes:
  readinessPath: "/health"
  livenessPath: "/health"

autoscaling:
  enabled: false

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"

securityContext:
  runAsUser: 101