serviceName: "frontend"
namespace: "cloudmart-prod"
replicaCount: 2

image:
  repository: "787308166325.dkr.ecr.ap-south-1.amazonaws.com/cloudmart/frontend"
  tag: "e69d5c34ca8eadea9f14db6bf3e6ab10c543c73d"

service:
  type: "ClusterIP"
  port: 80
  targetPort: 80

probes:
  readinessPath: "/health"
  livenessPath: "/health"

autoscaling:
  enabled: false

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"