# Production Environment Overrides
namespace: cloudmart-prod
replicaCount: 2  # High availability for production

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"