serviceName: "user-service"
namespace: "cloudmart-prod"
replicaCount: 2
serviceAccountName: "user-service-sa"

image:
  repository: "787308166325.dkr.ecr.ap-south-1.amazonaws.com/cloudmart/user-service"
  tag: "5e51b61bfaa13e745e33168669ff2108dcb09bb9"

service:
  type: "ClusterIP"
  port: 8003
  targetPort: 8003

probes:
  readinessPath: "/ready"
  livenessPath: "/health"

autoscaling:
  enabled: false

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

env:
  - name: PORT
    value: "8003"
  - name: DB_BACKEND
    valueFrom:
      configMapKeyRef: { name: cloudmart-config, key: USER_DB_BACKEND }
  - name: JWT_SECRET
    valueFrom:
      secretKeyRef: { name: cloudmart-secrets, key: JWT_SECRET }
  - name: DB_HOST
    valueFrom:
      configMapKeyRef: { name: cloudmart-config, key: DB_HOST }
  - name: DB_PORT
    valueFrom:
      configMapKeyRef: { name: cloudmart-config, key: DB_PORT }
  - name: DB_USER
    valueFrom:
      secretKeyRef: { name: cloudmart-secrets, key: DB_USER }
  - name: DB_NAME
    valueFrom:
      secretKeyRef: { name: cloudmart-secrets, key: DB_NAME }
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef: { name: cloudmart-secrets, key: DB_PASSWORD }