# ConfigMap for non-sensitive configuration
# Sensitive values (DB passwords, JWT secrets) should go in Kubernetes Secrets
# injected from your cloud provider's secret management service.
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudmart-config
  namespace: cloudmart-prod
data:
  # Global Environment Configuration
  AWS_REGION: "ap-south-1"

  # Product Service
  PRODUCT_STORE_BACKEND: "dynamodb"
  DYNAMODB_TABLE_NAME: "cloudmart-products"

  # Order Service
  PRODUCT_SERVICE_URL: "http://product-service:8001"
  ORDER_QUEUE_BACKEND: "sqs"
  SQS_QUEUE_URL: "https://sqs.ap-south-1.amazonaws.com/787308166325/cloudmart-orders"

  # Notification Service
  ORDER_SERVICE_URL: "http://order-service:8002"
  NOTIFICATION_QUEUE_BACKEND: "sqs"
  NOTIFICATION_EMAIL_BACKEND: "ses"
  NOTIFICATION_POLL_INTERVAL: "5000"
  FROM_EMAIL: "isuruvithanagemv@gmail.com"

  # User Service
  USER_DB_BACKEND: "postgres"
  DB_HOST: "cloudmart-postgres.c12wg4ugk0v1.ap-south-1.rds.amazonaws.com"
  DB_PORT: "5432"
---
# Staging environment ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudmart-config
  namespace: cloudmart-staging
data:
  # Global Environment Configuration
  AWS_REGION: "ap-south-1"

  # Product Service
  PRODUCT_STORE_BACKEND: "dynamodb"
  DYNAMODB_TABLE_NAME: "cloudmart-products"

  # Order Service
  PRODUCT_SERVICE_URL: "http://product-service:8001"
  ORDER_QUEUE_BACKEND: "sqs"
  SQS_QUEUE_URL: "https://sqs.ap-south-1.amazonaws.com/787308166325/cloudmart-orders"

  # Notification Service
  ORDER_SERVICE_URL: "http://order-service:8002"
  NOTIFICATION_QUEUE_BACKEND: "sqs"
  NOTIFICATION_EMAIL_BACKEND: "ses"
  NOTIFICATION_POLL_INTERVAL: "5000"
  FROM_EMAIL: "isuruvithanagemv@gmail.com"

  # User Service
  USER_DB_BACKEND: "postgres"
  DB_HOST: "cloudmart-postgres.c12wg4ugk0v1.ap-south-1.rds.amazonaws.com"
  DB_PORT: "5432"
