apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: cloudmart-prod
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1
      auth:
        jwt:
          serviceAccountRef:
            name: user-service-sa # Uses the IRSA role attached to this ServiceAccount
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudmart-db-secret
  namespace: cloudmart-prod
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: cloudmart-secrets # This matches what user-service.yaml is looking for!
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: arn:aws:secretsmanager:ap-south-1:854215217603:secret:cloudmart/user-service/db-password-4kc3jw
        property: DB_PASSWORD
    - secretKey: DB_NAME
      remoteRef:
        key: arn:aws:secretsmanager:ap-south-1:854215217603:secret:cloudmart/user-service/db-password-4kc3jw
        property: DB_NAME
    - secretKey: DB_USER
      remoteRef:
        key: arn:aws:secretsmanager:ap-south-1:854215217603:secret:cloudmart/user-service/db-password-4kc3jw
        property: DB_USER
    # We will generate a random JWT secret locally since it wasn't in Terraform
    - secretKey: JWT_SECRET
      remoteRef:
        key: arn:aws:secretsmanager:ap-south-1:854215217603:secret:cloudmart/user-service/db-password-4kc3jw
        property: DB_PASSWORD # Reusing the DB password string as a quick JWT secret for the assignment
